version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfg_rs/host.docker.internal:40001,host.docker.internal:40002,host.docker.internal:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017