apiVersion: v1
kind: Service
metadata:
  name: cs7ns6-api-svc
  labels:
    name: cs7ns6-api-svr
spec:
  type: LoadBalancer
  selector:
    app: cs7ns6-api-svr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

