apiVersion: v1
kind: Service
metadata:
  name: mongo-router-svc
  labels:
    name: mongo-router-svr
spec:
  type: LoadBalancer
  selector:
    app: mongo-router-svr
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
