apiVersion: v1
kind: Service
metadata:
  name: mongo-router-svc
  labels:
    name: mongo-router-svr
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30717
  selector:
    app: mongo-router-svr
