version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfg_rs/<YOUR_IP>:40001,<YOUR_IP>:40002,<YOUR_IP>:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017