version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfg_rs/10.6.56.67:40001,10.6.56.67:40002,10.6.56.67:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017