version: "3"

services:
  shard0_svr0:
    container_name: shard0_svr0
    image: mongo
    command: mongod --shardsvr --replSet shard0_rs --port 27017 --dbpath /data/db
    ports:
      - 50001:27017
    volumes:
      - shard0_svr0:/data/db

  shard0_svr1:
    container_name: shard0_svr1
    image: mongo
    command: mongod --shardsvr --replSet shard0_rs --port 27017 --dbpath /data/db
    ports:
      - 50002:27017
    volumes:
      - shard0_svr1:/data/db

  shard0_svr2:
    container_name: shard0_svr2
    image: mongo
    command: mongod --shardsvr --replSet shard0_rs --port 27017 --dbpath /data/db
    ports:
      - 50003:27017
    volumes:
      - shard0_svr2:/data/db

volumes:
  shard0_svr0: {}
  shard0_svr1: {}
  shard0_svr2: {}
